### ISSUE TITLE
problema login

### ISSUE THREAD

**Issue by luismoralesq** [peretch/facturacion#8]
buenas tardes amigo;
primero queria agradecer por tu aporte, estoy instalando tu sistema en local, pero tengo un inconveniente, no se cual es el usuario y la contraseña, pense en sacarlo de la base de datos pero la contraseña almacenada esta con encriptacion, la tabla users dice name:Administrador, email:dios y password:$2y$10$C8h8b2kGtLwqRpknatrlw.I3gRRs2LUu5af3j/gtlg7HwV7mAXieK 

intente acceder con el usuario y la contraseña que dejaste en la pregunta que te hicieron anteriormente pero solo funciona con el sistema que montaste de muestra, muchas gracias, espero su pronta respuesta

**Comment by peretch** [comment]
Hola Luis,

Esta info si te fijas dentro de `database/seeds/user_seeder.php`, verás que la info es la siguiente:

```
DB::table('users')->insert([
	'name' => 'Administrador',
	'email' => 'dios',
	'password' => bcrypt('mil@nes@'),
]);
```

Por tanto la contraseña es `mil@nes@`
